### ISSUE TITLE
One-click Heroku deploy

### ISSUE THREAD

**Issue by alainmeier** [alainmeier/cryptonote#12]
Add a [Heroku Button](https://devcenter.heroku.com/articles/heroku-button) to the README so that people can deploy their own CryptoNotes in a flash.

**Comment by Suleman-Elahi** [comment]
Error on deploying to Heroku...

![image](https://user-images.githubusercontent.com/24384996/68645129-11eb5200-053d-11ea-86aa-53d2ff0c5b09.png)
